language: go
go:
- 1.7.3
before_install:
- nvm install 7.2.0
- nvm use 7.2.0
- npm install
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get -qq update
- sudo apt-get install -y glide
- go get github.com/mattn/goveralls
- glide update
- glide install
script:
- go test $(glide nv)
- npm test --coverage
- ./coverage.bash
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken
  $COVERALLS_REPO_TOKEN
env:
  global:
    secure: CwXCKAZA6nDkZAKrO8GngqNScEuXpzBfGxEf0bqIMb7xM9K9Y7zAMvG6J04bGomwpskv19DU4WIVyZfrrCAv+pKY7TPHIeZDs1Ab7fYoG52V84yP7FncZmTBGdRX+Py9uLK8MM2qIbeNbdHqXIpRUI0LACapzCcaxoOJgghM5AcL+jzr5MmU/UFGupVhSz1Oz2ikON5Fuf979kpKphHXtvUlLSyGeodUF+CFRXghZ+mYKsGNZmB2OjaIYzxgrHRciYIRPuNFEWrf+9S9IACIQDySyoGAR5gI/6atEuAKTYqocnK8PnH3IQCLYBXGq7AOWZSz+hY+eSNCm3bohHgwBk65TyRBirQIl3F+IoNzpyRiVqT775Oh7L5Diu9K1Es7tQwQopimt6La3s+UT+iPXwvYfYfUt0njqKrQHC/Aa8tW9aGymmDE5GdfFcgwGNcTR93bNqQ3SDtWSgZoFy27A5uW8nG8ZlDPMRW1qi6Iv7SKOkAPzAv97SHwbVH7FqiFYC2qZ8fHJ8NARLsH3hPz0Vn72QL/PydzLwsfALOMlu2zNnOIQPMWWX1RL7j1TymQ5oDjzHhKKsxdA9KlOm93ENkY5YHovq5UlynPOVH58QmcPq154RZlIawoZ/vTjVbaWFsn2q0mYKUn7x7yDppm+X5Bmvxuvezoox861gQwSkg=
