language: go
go:
- 1.7.3
before_install:
- nvm install 7.2.0
- nvm use 7.2.0
- npm install
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get -qq update
- sudo apt-get install -y glide
- go get github.com/mattn/goveralls
- glide update
- glide install
script:
- go test $(glide nv)
- npm test --coverage
- ./coverage.bash
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken
  $COVERALLS_TOKEN
env:
  global:
    secure: njGddEGY8zIMpD+NUKHdKTmjprIpG1agvvql6FEbxYELZx74Sznc1M+1zdRuMyA3atzrPHhbf/tmrc3bQ387N+kZh7EB0va56w/cJM2/6cEuhnsPynevhiGlM8pfn89lnen44oHLVXUh+vSwtUR0zh4W5W0f45nrRXAm1iopyCq1H+02dZUCX+JbAcerCI/9GvBH5s7gZ2nZi+WBMAL6UwtrJI21S1UvAHS2DJIG98C5S6Vj7JWSwCY6C3BNtNf20kN9lX1kBGEkapBtqyqYCGxHtswNxOqGt/UzhQln/zFHXL6qqwYGqe3PHFSSgyxSgKLZNkhUO1nXNW0GqUvfWe6bPZzpxqLAgnjzl+CZkuuuVVGSHCgltk1TOZQa/zo93H4V4Cax3xdRuRRDGtf4NjRi5+t63VGFwkX7ffJTzqOwbdEaZRlybbBDpVarJrliCKN0UpqO5PObzDoUcMl1UAvdFU6j/xs2+c3qm2dsfpKcxmH2/+0FsQVxQK6S1+WJLW5FAr+F+wqLgOQC2tkymFaft4TIhVabCJFBahVmWbHU4D2zc6H9+RWaDFDVMrxQcWPN3qjKiaagdScpuTFsf1JMB9Bdzfpzt3GEMen/FtuFh4AbkLRlaPuYUD1qJobGNMARaiKhhhS8ehJGqmRmjKgdpU8fJgGOsbTAgzdWr3o=
