---
- hosts: all
  become: yes
  tasks:
    - name: add mongo apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0C49F3730359A14518585931BC711F9BA15703C6
        state: present

    - name: add MongoDB stable repository (for Ubuntu)
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse
        state: present

    - name: Install apt packages
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - git
        - golang
        - runit
        - mongodb

    # - name: ensure database is created
    #   command: mongo monmach
    #   args:
    #     chdir: /srv/monmach-api/

    - name: Clone repo
      git: repo=https://github.com/avidreder/monmach-api.git dest=/srv/monmach-api version=master force=yes
      ignore_errors: yes

    - name: Create monmach-api rundir for runit
      file:
        path: /etc/sv/monmach-api
        state: directory
        mode: 0755

    - name: Install monmach runfile for runit
      copy:
        src: runit_monmach_api.run
        dest: /etc/sv/monmach-api/run
        mode: 0751

    - name: Install spotify credentials
      copy:
        src: spotify.json
        dest: /srv/monmach-api/spotify.json
        mode: 0777

    - name: Install monmach-api binary
      copy:
        src: monmach-api
        dest: /srv/monmach-api/monmach-api
        mode: 0777

    - name: Install service config
      copy:
        src: config/localhost.json
        dest: /srv/monmach-api/localhost.json
        mode: 0777

    - file: path=/tmp state=directory mode=0777

    - name: fix owner/group
      file:
        path: /srv/monmach-api/monmach-api
        owner: root
        group: root

    - name: Put monmach-api in runit
      file:
        path: /etc/sv/monmach-api/monmach-api
        src: /srv/monmach-api/monmach-api
        state: link

    - name: Activate monmach-api in runit
      file:
        path: /etc/service/monmach-api
        src: /etc/sv/monmach-api
        state: link
